from __future__ import annotations
from typing import Protocol, Optional
from app.domain.metadata import ImageMetadata

class MetadataRepository(Protocol):
    def upsert(self, meta: ImageMetadata) -> None: ...
    def get(self, uuid: str) -> Optional[ImageMetadata]: ...
    def delete(self, uuid: str) -> None: ...
