# app/contracts/metadata_repository.py

from __future__ import annotations
from typing import Protocol, Optional, Sequence, Tuple, Iterable
from app.domain.metadata import ImageMetadata

class MetadataRepository(Protocol):
    def upsert(self, meta: ImageMetadata) -> None: ...
    def get(self, uuid: str) -> Optional[ImageMetadata]: ...
    def delete(self, uuid: str) -> None: ...
    def list(self, *, limit: int, offset: int) -> Tuple[Sequence[ImageMetadata], int]: ... # возвращает Items и total
    def iter_uuids(self, *, batch_size: int = 1000) -> Iterable[str]: ...
    def delete_all(self) -> int: ...

# Всё, что нужно бизнес-логике (services) — должно быть в contracts.